spring.application.name=Linkedin-Clone

spring.datasource.url=jdbc:mysql://localhost:3306/LinkedIn_clone
spring.datasource.username=root
spring.datasource.password=Rishav@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# ==========================
# Enable Debug Logging
# ==========================
logging.level.org.springframework.security=DEBUG
logging.level.com.Assignemnt.Linkedin.Clone.security=DEBUG
